/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteTransferRequest { 
    /**
     * Ingestion id to abort the ingestion
     */
    ingestId?: string;
}

