/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeleteTransferResponse { 
    /**
     * Transfer id affected
     */
    transferId: string;
    /**
     * New status of the transfer.
     */
    status?: string;
}

