/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostDatasetResponse { 
    /**
     * The unique ingestion id of the dataset.
     */
    ingestId?: string;
    /**
     * The status of the ingestion. Can be used to send a message back to the ui.
     */
    status?: string;
}

