FROM node:9.1
LABEL maintainer="gareth.murphy@esss.se"

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends \
    chromium \
    && rm -rf /var/lib/apt/lists/*
    
RUN sudo npm install -g chromedriver

ENV CHROME_BIN /usr/bin/chromium

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm install
COPY . /usr/src/app
WORKDIR /usr/src/app
