node {
       stage('Checkout'){

          checkout scm
       }


       stage('Build Docker'){
            sh '/usr/bin/docker build -f CI/PSI/Dockerfile.test . -t catanie_test'
       }
       stage('Unit Test Catanie '){
            sh 'docker run  --privileged -t catanie_test npm run -- ng test --watch false --single-run true --sourcemap false'
       }
       stage('e2e Test Catanie '){
            sh 'docker run  --privileged -t catanie_test ./node_modules/@angular/cli/bin/ng e2e -e qa'
       }

}
