export const environment = {
  production: true,
  lbBaseURL: "https://dacat.psi.ch",
  externalAuthEndpoint: "/auth/msad",
  archiveWorkflowEnabled: true,
  editMetadataEnabled: false,
  editSampleEnabled: false,
  scienceSearchEnabled: false,
  disabledDatasetColumns: ["image"],
  facility: "PSI",
  multipleDownloadEnabled: false,
  shoppingCartEnabled: false,
  columnSelectEnabled: false,
  userProfileImageEnabled: false,
  ingestManual: "https://melanie.gitpages.psi.ch/SciCatPages/",
  gettingStarted: "https://melanie.gitpages.psi.ch/SciCatPages/SciCatGettingStartedSLSSummary.pdf",
  logbookEnabled: false,
  tableSciDataEnabled: false,
  metadataPreviewEnabled: false,
  datasetReduceEnabled: false,
  fileColorEnabled: false,
  landingPage: "doi.psi.ch/detail/"
};
