import { TableColumn } from "state-management/models";

// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular-cli.json`.

export const environment = {
  production: false,
  lbBaseURL: "http://127.0.0.1:3000",
  fileserverBaseURL: "/fileserver",
  synapseBaseUrl: "https://scitest.maxiv.lu.se",
  riotBaseUrl: "http://scichat.maxiv.lu.se",
  jupyterHubUrl: "https://jupyterhub.maxiv.lu.se",
  externalAuthEndpoint: "/auth/msad",
  addDatasetEnabled: true,
  archiveWorkflowEnabled: true,
  columnSelectEnabled: true,
  csvEnabled: true,
  datasetReduceEnabled: true,
  disabledDatasetColumns: [
    "select",
    "archiveStatus",
    "retrieveStatus",
    "ownerGroup",
  ],
  editMetadataEnabled: true,
  editSampleEnabled: true,
  editPublishedData: true,
  facility: "MAX IV",
  fileColorEnabled: true,
  jobsEnabled: true,
  policiesEnabled: true,
  localColumns: [
    { name: "select", order: 0, type: "standard", enabled: true },
    { name: "datasetName", order: 1, type: "standard", enabled: true },
    { name: "runNumber", order: 2, type: "standard", enabled: true },
    { name: "sourceFolder", order: 3, type: "standard", enabled: true },
    { name: "size", order: 4, type: "standard", enabled: true },
    { name: "creationTime", order: 5, type: "standard", enabled: true },
    { name: "type", order: 6, type: "standard", enabled: true },
    { name: "image", order: 7, type: "standard", enabled: true },
    { name: "metadata", order: 8, type: "standard", enabled: true },
    { name: "proposalId", order: 9, type: "standard", enabled: true },
    { name: "ownerGroup", order: 10, type: "standard", enabled: false },
    { name: "dataStatus", order: 11, type: "standard", enabled: false },
    { name: "derivedDatasetsNum", order: 12, type: "standard", enabled: false },
  ] as TableColumn[],
  landingPage: "doi-test.maxiv.lu.se/detail/",
  logbookEnabled: false,
  metadataPreviewEnabled: false,
  fileDownloadEnabled: false,
  multipleDownloadEnabled: false,
  maxDirectDownloadSize: 5000000000,
  multipleDownloadAction: "https://zip-service.maxiv.lu.se/zip",
  scienceSearchEnabled: true,
  scienceSearchUnitsEnabled: true,
  searchProposals: true,
  searchPublicDataEnabled: false,
  searchSamples: true,
  sftpHost: "",
  shoppingCartEnabled: true,
  shoppingCartOnHeader: true,
  tableSciDataEnabled: true,
  metadataStructure: "tree",
  userNamePromptEnabled: true,
  userProfileImageEnabled: true,
  jsonMetadataEnabled: true,
  editDatasetSampleEnabled:false

};
