
// First day of week for locale
//  0: Sunday
//  1: Monday
//  6: Saturday
// Note iso default is Monday, whereas javascript's day indexing implies a default of Sunday

// data sources:

// [salesforce]
// salesforce data based off of manually mapping information from the following
//   https://help.salesforce.com/articleView?id=000229511&type=1
//     (archived at https://archive.is/zzoJg)
// (after manually mapping to the following)
//   https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
//     (archived at https://archive.is/GGQQ7; last updated 2017-08-15)

// [momentjs]
//   first day of week indices from momentjs locale files
//    https://github.com/moment/moment/tree/develop/locale
//    manually touched up capitalization (for entries including a dash)
//    note that some entries contradict what other sources say


interface IStringToNumDict {
    [key: string]: number;
}

export const fdowi: IStringToNumDict = {
    'gom-Latn': 1, // (momentjs)
    'sr-Cyrl': 1, // (momentjs)
    'tzm-Latn': 6, // (momentjs)
    'uz-Latn': 1, // (momentjs)
    'uz-Latn-UZ': 0, // (salesforce)
    'ar-LY': 6, // (momentjs & salesforce)
    'ar-MA': 6, // (momentjs & salesforce)
    'de-AT': 1, // (momentjs & salesforce)
    'de-CH': 1, // (momentjs & salesforce)
    'en-GB': 1, // (momentjs & salesforce)
    'en-IE': 1, // (momentjs & salesforce)
    'es-DO': 1, // (momentjs & salesforce)
    'fr-CH': 1, // (momentjs & salesforce)
    'nl-BE': 1, // (momentjs & salesforce)
    'pa-IN': 0, // (momentjs)
    'ar-AE': 6, // (salesforce)
    'ar-BH': 6, // (salesforce)
    'ar-EG': 0, // (salesforce)
    'ar-IQ': 0, // (salesforce)
    'ar-JO': 6, // (salesforce)
    'ar-LB': 6, // (salesforce)
    'ar-OM': 6, // (salesforce)
    'ar-QA': 6, // (salesforce)
    'ar-SD': 6, // (salesforce)
    'ar-SY': 6, // (salesforce)
    'ar-YE': 6, // (salesforce)
    'az-AZ': 0, // (salesforce)
    'be-BY': 0, // (salesforce)
    'bg-BG': 0, // (salesforce)
    'bn-BD': 0, // (salesforce)
    'bs-BA': 0, // (salesforce)
    'ca-ES': 1, // (salesforce)
    'cs-CZ': 1, // (salesforce)
    'cy-GB': 0, // (salesforce)
    'de-DE': 1, // (salesforce)
    'de-LU': 1, // (salesforce)
    'dz-BT': 0, // (salesforce)
    'el-GR': 1, // (salesforce)
    'en-AG': 0, // (salesforce)
    'en-BB': 0, // (salesforce)
    'en-BM': 0, // (salesforce)
    'en-BS': 0, // (salesforce)
    'en-BW': 0, // (salesforce)
    'en-BZ': 0, // (salesforce)
    'en-CA': 0, // (salesforce)
    'en-CM': 0, // (salesforce)
    'en-ER': 0, // (salesforce)
    'en-FJ': 0, // (salesforce)
    'en-FK': 0, // (salesforce)
    'en-GH': 0, // (salesforce)
    'en-GI': 0, // (salesforce)
    'en-GM': 0, // (salesforce)
    'en-GY': 0, // (salesforce)
    'en-HK': 0, // (salesforce)
    'en-ID': 0, // (salesforce)
    'en-IN': 0, // (salesforce)
    'en-JM': 0, // (salesforce)
    'en-KE': 0, // (salesforce)
    'en-KY': 0, // (salesforce)
    'en-LR': 0, // (salesforce)
    'en-MG': 0, // (salesforce)
    'en-MU': 0, // (salesforce)
    'en-MW': 0, // (salesforce)
    'en-MY': 0, // (salesforce)
    'en-NA': 0, // (salesforce)
    'en-NG': 0, // (salesforce)
    'en-PG': 0, // (salesforce)
    'en-PH': 0, // (salesforce)
    'en-PK': 0, // (salesforce)
    'en-SB': 0, // (salesforce)
    'en-SC': 0, // (salesforce)
    'en-SG': 0, // (salesforce)
    'en-SH': 0, // (salesforce)
    'en-SL': 0, // (salesforce)
    'en-SX': 0, // (salesforce)
    'en-SZ': 0, // (salesforce)
    'en-TO': 0, // (salesforce)
    'en-TT': 0, // (salesforce)
    'en-TZ': 0, // (salesforce)
    'en-UG': 0, // (salesforce)
    'en-US': 0, // (salesforce)
    'en-VU': 0, // (salesforce)
    'en-WS': 0, // (salesforce)
    'en-ZA': 0, // (salesforce)
    'es-AR': 1, // (salesforce)
    'es-BO': 1, // (salesforce)
    'es-CL': 1, // (salesforce)
    'es-CO': 1, // (salesforce)
    'es-CR': 1, // (salesforce)
    'es-CU': 1, // (salesforce)
    'es-EC': 1, // (salesforce)
    'es-ES': 1, // (salesforce)
    'es-GT': 1, // (salesforce)
    'es-HN': 1, // (salesforce)
    'es-MX': 1, // (salesforce)
    'es-NI': 1, // (salesforce)
    'es-PA': 1, // (salesforce)
    'es-PE': 1, // (salesforce)
    'es-PR': 1, // (salesforce)
    'es-PY': 1, // (salesforce)
    'es-SV': 1, // (salesforce)
    'es-US': 0, // (salesforce)
    'es-UY': 1, // (salesforce)
    'es-VE': 1, // (salesforce)
    'et-EE': 1, // (salesforce)
    'eu-ES': 0, // (salesforce)
    'fa-IR': 0, // (salesforce)
    'fi-FI': 1, // (salesforce)
    'fr-BE': 1, // (salesforce)
    'fr-CA': 0, // (salesforce)
    'fr-FR': 1, // (salesforce)
    'fr-GN': 1, // (salesforce)
    'fr-HT': 1, // (salesforce)
    'fr-KM': 1, // (salesforce)
    'fr-LU': 1, // (salesforce)
    'fr-MC': 1, // (salesforce)
    'fr-MR': 1, // (salesforce)
    'fr-WF': 1, // (salesforce)
    'ga-IE': 0, // (salesforce)
    'he-IL': 0, // (salesforce)
    'hi-IN': 0, // (salesforce)
    'hr-HR': 1, // (salesforce)
    'hu-HU': 1, // (salesforce)
    'id-ID': 1, // (salesforce)
    'is-IS': 1, // (salesforce)
    'it-CH': 1, // (salesforce)
    'it-IT': 1, // (salesforce)
    'ja-JP': 0, // (salesforce)
    'kk-KZ': 0, // (salesforce)
    'km-KH': 0, // (salesforce)
    'ko-KP': 0, // (salesforce)
    'ko-KR': 0, // (salesforce)
    'ky-KG': 0, // (salesforce)
    'lb-LU': 0, // (salesforce)
    'lo-LA': 0, // (salesforce)
    'lt-LT': 1, // (salesforce)
    'lu-CD': 0, // (salesforce)
    'lv-LV': 0, // (salesforce)
    'mk-MK': 0, // (salesforce)
    'ms-BN': 0, // (salesforce)
    'mt-MT': 0, // (salesforce)
    'my-MM': 0, // (salesforce)
    'ne-NP': 0, // (salesforce)
    'nl-AW': 1, // (salesforce)
    'nl-NL': 1, // (salesforce)
    'nl-SR': 1, // (salesforce)
    'no-NO': 1, // (salesforce)
    'pl-PL': 1, // (salesforce)
    'ps-AF': 0, // (salesforce)
    'pt-AO': 1, // (salesforce)
    'pt-BR': 0, // (salesforce)
    'pt-CV': 1, // (salesforce)
    'pt-MZ': 1, // (salesforce)
    'pt-PT': 1, // (salesforce)
    'pt-ST': 1, // (salesforce)
    'rm-CH': 0, // (salesforce)
    'rn-BI': 0, // (salesforce)
    'ro-MD': 1, // (salesforce)
    'ro-RO': 1, // (salesforce)
    'ru-RU': 1, // (salesforce)
    'sh-BA': 1, // (salesforce)
    'sk-SK': 1, // (salesforce)
    'sl-SI': 1, // (salesforce)
    'so-DJ': 0, // (salesforce)
    'so-SO': 0, // (salesforce)
    'sq-AL': 6, // (salesforce)
    'sr-BA': 1, // (salesforce)
    'sr-CS': 1, // (salesforce)
    'sr-ME': 1, // (salesforce)
    'sr-RS': 0, // (salesforce)
    'sv-SE': 1, // (salesforce)
    'ta-IN': 0, // (salesforce)
    'ta-LK': 0, // (salesforce)
    'tg-TJ': 0, // (salesforce)
    'th-TH': 0, // (salesforce)
    'ti-ET': 0, // (salesforce)
    'tr-TR': 1, // (salesforce)
    'uk-UA': 1, // (salesforce)
    'ur-PK': 0, // (salesforce)
    'vi-VN': 0, // (salesforce)
    'yo-BJ': 0, // (salesforce)
    'zh-HK': 0, // (salesforce)
    'zh-SG': 0, // (salesforce)
    'zh-TW': 0, // (salesforce)
    'ar-DZ': 0, // (momentjs: 0, salesforce: 6) conflicting info
    'ar-KW': 0, // (momentjs: 0, salesforce: 6) conflicting info
    'ar-SA': 0, // (momentjs: 0, salesforce: 6) conflicting info
    'ar-TN': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'en-AU': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'en-NZ': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'hy-AM': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'ms-MY': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'tl-PH': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'zh-CN': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'bn': 0, // (momentjs & salesforce)
    'ca': 1, // (momentjs & salesforce)
    'cs': 1, // (momentjs & salesforce)
    'de': 1, // (momentjs & salesforce)
    'el': 1, // (momentjs & salesforce)
    'et': 1, // (momentjs & salesforce)
    'fi': 1, // (momentjs & salesforce)
    'fr': 1, // (momentjs & salesforce)
    'hi': 0, // (momentjs & salesforce)
    'hu': 1, // (momentjs & salesforce)
    'is': 1, // (momentjs & salesforce)
    'it': 1, // (momentjs & salesforce)
    'nl': 1, // (momentjs & salesforce)
    'af': 1, // (momentjs)
    'ar': 6, // (momentjs)
    'az': 1, // (momentjs)
    'be': 1, // (momentjs)
    'bo': 0, // (momentjs)
    'br': 1, // (momentjs)
    'cv': 1, // (momentjs)
    'cy': 1, // (momentjs)
    'da': 1, // (momentjs)
    'dv': 0, // (momentjs)
    'eo': 1, // (momentjs)
    'es': 1, // (momentjs)
    'fa': 6, // (momentjs)
    'fo': 1, // (momentjs)
    'fy': 1, // (momentjs)
    'gd': 1, // (momentjs)
    'gl': 1, // (momentjs)
    'jv': 1, // (momentjs)
    'kk': 1, // (momentjs)
    'km': 1, // (momentjs)
    'kn': 0, // (momentjs)
    'ky': 1, // (momentjs)
    'lb': 1, // (momentjs)
    'lt': 1, // (momentjs)
    'lv': 1, // (momentjs)
    'me': 1, // (momentjs)
    'mi': 1, // (momentjs)
    'mk': 1, // (momentjs)
    'mr': 0, // (momentjs)
    'ms': 1, // (momentjs)
    'my': 1, // (momentjs)
    'nb': 1, // (momentjs)
    'ne': 0, // (momentjs)
    'nn': 1, // (momentjs)
    'pl': 1, // (momentjs)
    'pt': 1, // (momentjs)
    'ro': 1, // (momentjs)
    'ru': 1, // (momentjs)
    'sd': 1, // (momentjs)
    'se': 1, // (momentjs)
    'sk': 1, // (momentjs)
    'sl': 1, // (momentjs)
    'sq': 1, // (momentjs)
    'sr': 1, // (momentjs)
    'ss': 1, // (momentjs)
    'sv': 1, // (momentjs)
    'sw': 1, // (momentjs)
    'ta': 0, // (momentjs)
    'te': 0, // (momentjs)
    'tet': 1, // (momentjs)
    'tlh': 1, // (momentjs)
    'tr': 1, // (momentjs)
    'tzl': 1, // (momentjs)
    'tzm': 6, // (momentjs)
    'uk': 1, // (momentjs)
    'ur': 1, // (momentjs)
    'uz': 1, // (momentjs)
    'vi': 1, // (momentjs)
    'yo': 1, // (momentjs)
    'ga': 0, // (salesforce)
    'he': 0, // (salesforce)
    'hy': 0, // (salesforce)
    'ja': 0, // (salesforce)
    'zh': 0, // (salesforce)
    'bg': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'bs': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'eu': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'hr': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'id': 1, // (momentjs: 1, salesforce: 0) conflicting info
    'ka': 1, // (momentjs: 1, salesforce: 0) conflicting info
};
