/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * a method item describes the method\'s name and schema
 */
export interface FolderNode { 
    name: string;
    path: string;
    children: boolean;
    probablyDataset: boolean;
}

