/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FolderNode } from './folderNode';


export interface GetBrowseDatasetResponse { 
    folders: Array<FolderNode>;
    /**
     * Total number of folders.
     */
    total: number;
}

