/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetDatasetResponse { 
    datasets: Array<string>;
    /**
     * Total number of datasets.
     */
    total: number;
}

