/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MethodItem } from './methodItem';


export interface GetExtractorResponse { 
    /**
     * List of the metadata extraction method names configured in the ingestor
     */
    methods: Array<MethodItem>;
    /**
     * Total number of methods
     */
    total: number;
}

