/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferItem } from './transferItem';


export interface GetTransferResponse { 
    transfers?: Array<TransferItem>;
    /**
     * Total number of transfers.
     */
    total?: number;
}

