/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * OIDC UserInfo object
 */
export interface OidcCallbackOkUserInfo { 
    /**
     * subject of user
     */
    sub: string;
    profile: string;
    email: string;
    email_verified: boolean;
}

