/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Oauth2 Token object
 */
export interface OidcCallbackOkOAuth2Token { 
    access_token: string;
    token_type?: string;
    refresh_token?: string;
    expiry?: string;
    expires_in?: number;
}

