/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OtherHealthResponse { 
    /**
     * Status of the ingestor.
     */
    status: string;
    errors?: { [key: string]: string; };
}

