/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostDatasetResponse { 
    /**
     * The unique transfer id of the dataset transfer job.
     */
    transferId: string;
    /**
     * The status of the transfer. Can be used to send a message back to the ui.
     */
    status?: string;
}

