/**
 * SciCat Ingestor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    logged_in: boolean;
    subject?: string;
    profile?: string;
    email?: string;
    roles?: Array<string>;
    preferred_username?: string;
    name?: string;
    family_name?: string;
    given_name?: string;
    expires_at?: string;
}

