FROM markadams/chromium-xvfb-js:8
LABEL maintainer="gareth.murphy@esss.se"
ENV http_proxy "http://192.168.1.1:8123"
ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"

RUN apt-get update && apt-get install -y git

RUN npm config set proxy  $http_proxy
RUN npm config set https-proxy  $http_proxy
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
COPY package.json /usr/src/app/package.json
RUN npm install
COPY . /usr/src/app
COPY CI/ESS/karma.conf.js /project/catanie/
WORKDIR /usr/src/app
# RUN npm run -- ng test --watch false --single-run true
