FROM node:9
EXPOSE 80

RUN apt-get update && apt-get install -y nginx

RUN mkdir /usr/html
RUN mkdir /catanie
WORKDIR /catanie


COPY ../../package.json .
RUN npm i

COPY ../../src src
COPY ../../angular-cli.json .

ARG APP_PROD='true'
ARG LB_BASE_URL='http://localhost/api'
ARG LB_API_VERSION=''


RUN npx ng build --environment=dev
RUN mv dist/* /usr/html
