FROM cypress/included:9.2.1
LABEL maintainer="henrik.johansson@ess.eu"

RUN apt-get update && apt-get install -y wget

ARG env=dmscdev

WORKDIR /e2e

COPY package*.json  ./
RUN npm ci
#RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh
COPY . ./
