FROM cypress/base
LABEL maintainer="gareth.murphy@esss.se"
RUN sed -i -e 's/^root::/root:!:/' /etc/shadow

RUN apt-get update && apt-get install -y wget
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
ARG env=dmscdev
WORKDIR /catanie
COPY package.json  /catanie
RUN npm install
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x wait-for-it.sh
COPY . /catanie/