FROM nginx 

RUN apt-get update && apt-get install -y apt-transport-https lsb-release curl gnupg2 git

RUN curl -sL https://deb.nodesource.com/setup_9.x |  bash -

RUN apt-get install -y nodejs



ARG env=dev
WORKDIR /catanie
COPY package.json  /catanie

RUN npm install
COPY . /catanie/
RUN npx ng build --environment=${env}

COPY scripts/nginx.conf /etc/nginx/nginx.conf
RUN cp -r  dist/* /usr/share/nginx/html/

RUN ls /usr/share/nginx/html/
EXPOSE 80
