
node {
       stage('Checkout'){

          checkout scm
       }


       stage('Build Docker'){

            sh 'docker build -f CI/ESS/Dockerfile.test . -t catanie_test'
       }
       stage('Unit Test Catanie '){
            sh 'docker run  -t catanie_test npm run -- ng test --watch false --single-run true'
       }
       stage('e2e Test Catanie '){
            sh 'docker run  -t catanie_test npm run e2e'
       }

}
