FROM ghcr.io/scicatproject/backend-next:latest

USER root

RUN apk add --no-cache wget

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
    && chmod +x wait-for-it.sh \
    && mv wait-for-it.sh /usr/local/bin

COPY . /backend/
