version: "3.4"
services:
  reverse-proxy:
    image: traefik:2.10
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    ## As of 2024-10-22 bitnami mongoDB still do not support ARM64
    ## Change back to bitnami/mongodb when it supports ARM64
    image: "mongo:latest" 
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    image: ghcr.io/scicatproject/backend-next:latest
    ports:
      - 3000:3000
    volumes:
      - "./CI/e2e/.env.backend.e2e:/home/node/app/.env"
      - "./CI/e2e/functionalAccounts.e2e.json:/home/node/app/functionalAccounts.json"
      - "./CI/e2e/proposalTypes.e2e.json:/home/node/app/proposalTypes.json"
      - "./CI/e2e/frontend.config.e2e.json:/home/node/app/dist/config/frontend.config.json"
      - "./CI/e2e/frontend.theme.e2e.json:/home/node/app/dist/config/frontend.theme.json"
      - "./CI/e2e/publishedDataConfig.e2e.json:/home/node/app/publishedDataConfig.json"
    environment:
      - DOI_USERNAME=${DOI_USERNAME}
      - DOI_PASSWORD=${DOI_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v3/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/v3`, `/auth/msad`)"
      - "traefik.http.routers.backend.entrypoints=web"
  frontend:
    build:
      context: .
    ports:
      - 4200:8080
    volumes:
      - "./CI/e2e/frontend.config.e2e.json:/usr/share/nginx/html/assets/config.json"
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"

volumes:
  mongodb_data:
    driver: local
