FROM node:14-alpine3.12
RUN sed -i -e 's/^root::/root:!:/' /etc/shadow
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
# ARG serve-env=alsdev
WORKDIR /scicat_frontend
COPY package.json  /scicat_frontend
RUN npm install
COPY . /scicat_frontend/
# COPY CI/ALS/environment.als.dev.ts src/environments/environment.als.dev.ts
# RUN npx ng build --configuration=${env}
ENTRYPOINT ./node_modules/@angular/cli/bin/ng serve --host $HOST --port 80 --configuration=alsdev



EXPOSE 80