FROM node:12.6.0-alpine as builder
LABEL maintainer="gareth.murphy@esss.se"
RUN sed -i -e 's/^root::/root:!:/' /etc/shadow
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
ARG env=als-dev
WORKDIR /catanie
COPY package.json  /catanie
RUN npm install
COPY . /catanie/
COPY CI/ALS/environment.als.dev.ts src/environments/environment.als.dev.ts
RUN npx ng build --configuration=${env}
ENTRYPOINT ./node_modules/@angular/cli/bin/ng serve --host $HOST --port 80



EXPOSE 80
